---
- name: Install flaskex on Ubuntu 18.04
  hosts: all
  gather_facts: no

  tasks:

    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes
      become: yes

    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present
      become: yes
     
    - name: Git pull flaskex
      git:
        repo: 'https://github.com/anfederico/flaskex.git'
        dest: ~/flaskex

    - name: Set WTForms version in requirments.txt
      replace:
        path: ~/flaskex/requirements.txt
        regexp: 'WTForms'
        replace: 'WTForms==1.0.1'
        #              sed -i 's/WTForms/WTForms==1.0.1/' ~/flaskex/requirements.txt

    - name: pip requirements is installed
      pip:
        requirements: ~/flaskex/requirements.txt

